spring:
  application:
    name: microsservico_notificacao
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

aws:
  region: us-east-1
  sns:
    endpoint: http://localhost:4566

rabbitmq:
  queue:
    proposta:
      pendente: proposta-pendente.ms-notificacao