spring:
  application:
    name: analise-credito
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

rabbitmq:
  propostaconcluida:
    exchange: proposta-concluida.ex
  queue:
    proposta:
      analise: proposta-pendente.ms-analise-credito
