spring:
  application:
    name: banking-credit-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/banking_credit_gateway
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3

rabbitmq:
  exchange:
    proposta-pendente: proposta-pendente.ex
    proposta-concluida: proposta-concluida.ex
    dead-letter: dead-letter.ex
  queue:
    analise-credito: proposta-pendente.ms-analise-credito
    notificacao-pendente: proposta-pendente.ms-notificacao
    proposta: proposta-concluida.ms-proposta
    notificacao-concluida: proposta-concluida.ms-notificacao
  dlq:
    analise-credito: proposta-pendente.ms-analise-credito.dlq
    notificacao-pendente: proposta-pendente.ms-notificacao.dlq
    proposta: proposta-concluida.ms-proposta.dlq
    notificacao-concluida: proposta-concluida.ms-notificacao.dlq